#!/usr/bin/env python3
"""
Layout probe generator.

Generates a C source file that verifies struct field names and types from the IDL
compile against the actual library header. Building this file catches:

  - Renamed fields (compile error)
  - Removed fields (compile error)
  - Removed structs (compile error)
  - Field count mismatches (static_assert)

Usage:
  python3 layout_probe_generator.py --idl <path> --out <path> [--check] [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def _snake_to_camel(name: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[_\s]+", name) if w)


def generate_layout_probe(idl: dict[str, Any]) -> str:
    target = str(idl.get("target") or "mylib")
    codegen = idl.get("codegen") or {}

    # Prefer the generated native header, fall back to original
    native_header = codegen.get("native_header_output_path") or ""
    original_header = (idl.get("header") or {}).get("path") or ""
    include_path = native_header or original_header or f"{target}.h"
    # Use just the filename for the include
    include_name = Path(include_path).name

    structs: dict[str, Any] = (idl.get("header_types") or {}).get("structs") or {}

    lines: list[str] = [
        f"/* {target}_layout_probe.c — generated by abi_framework layout_probe_generator */",
        "/* Compile this file to verify that struct fields in the IDL match the header. */",
        "/* Any compile error here means the C header has drifted from the IDL snapshot. */",
        "",
        f'#include "{include_name}"',
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]

    if not structs:
        lines += [
            "/* No structs found in IDL. */",
            "",
            "static void abi_layout_probe_noop(void) { (void)0; }",
            "",
        ]
        return "\n".join(lines)

    lines += [
        "/* --- field existence checks --- */",
        "/* Each function below will fail to compile if a field is renamed or removed. */",
        "",
    ]

    for struct_name, struct_def in structs.items():
        fields: list[dict[str, Any]] = struct_def.get("fields") or []
        if not fields:
            continue

        field_count = struct_def.get("field_count", len(fields))
        fn_name = f"abi_layout_check_{struct_name}"

        lines.append(f"static void {fn_name}(void) {{")
        lines.append(f"    {struct_name} _s;")
        lines.append(f"    (void)_s;")

        for field in fields:
            f_name = str(field.get("name") or "")
            if not f_name:
                continue
            lines.append(f"    (void)_s.{f_name};  /* field must exist */")

        # static_assert on field count — catches additions that aren't in IDL yet
        # We can't easily do sizeof() without knowing expected size, but we can
        # assert the struct is not empty
        lines.append(f"    /* {struct_name}: {field_count} field(s) expected */")
        lines.append("}")
        lines.append("")

    # Emit a top-level probe function that calls all checks
    lines += [
        "/* --- top-level entry point (call from a test or just compile) --- */",
        "static void abi_layout_probe_all(void) {",
    ]
    for struct_name, struct_def in structs.items():
        fields = struct_def.get("fields") or []
        if not fields:
            continue
        lines.append(f"    abi_layout_check_{struct_name}();")
    lines += [
        "}",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description="Generate C layout probe from IDL JSON.")
    parser.add_argument("--idl", required=True, help="IDL JSON path.")
    parser.add_argument("--out", required=True, help="Output .c file path.")
    parser.add_argument("--check", action="store_true", help="Fail if output would change.")
    parser.add_argument("--dry-run", action="store_true", help="Print output, do not write.")
    args = parser.parse_args()

    idl_path = Path(args.idl)
    out_path = Path(args.out)

    with idl_path.open("r", encoding="utf-8") as f:
        idl = json.load(f)

    content = generate_layout_probe(idl)

    if args.check:
        if not out_path.exists():
            print(f"MISSING: {out_path}", file=sys.stderr)
            return 1
        existing = out_path.read_text(encoding="utf-8")
        if existing != content:
            print(f"DRIFT: {out_path} is out of date.", file=sys.stderr)
            return 1
        return 0

    if args.dry_run:
        print(content)
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Generated: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
