#!/usr/bin/env python3
"""
Native impl handles header generator.

Reads native_impl_handles from managed_api metadata JSON and emits a C++ header
with struct definitions for opaque handle implementation types.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

TOOL_PATH = "generator_sdk/native_impl_handles_generator.py"

try:
    import abi_codegen_core  # noqa: F401
except ImportError:
    _CORE_SRC = Path(__file__).resolve().parents[1] / "abi_codegen_core" / "src"
    if str(_CORE_SRC) not in sys.path:
        sys.path.insert(0, str(_CORE_SRC))

from abi_codegen_core.common import load_json_object, write_if_changed


def render(metadata: dict[str, Any]) -> str:
    handles = metadata.get("native_impl_handles")
    if not isinstance(handles, list):
        raise SystemExit("managed_api.native_impl_handles must be an array")

    lines: list[str] = [
        "// <auto-generated />",
        f"// Generated by {TOOL_PATH}",
        "#pragma once",
        "",
    ]

    seen: set[str] = set()
    for i, item in enumerate(handles):
        ctx = f"native_impl_handles[{i}]"
        if not isinstance(item, dict):
            raise SystemExit(f"{ctx} must be an object")
        name = item.get("name")
        if not isinstance(name, str) or not name:
            raise SystemExit(f"{ctx}.name must be a non-empty string")
        if name in seen:
            raise SystemExit(f"Duplicate native_impl_handles entry '{name}'")
        seen.add(name)
        fields = item.get("fields")
        if not isinstance(fields, list):
            raise SystemExit(f"{ctx}.fields must be an array")

        lines.append(f"struct {name} {{")
        for field in fields:
            if not isinstance(field, str):
                raise SystemExit(f"{ctx}.fields entries must be strings")
            lines.append(f"  {field}")
        lines.append("};")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate C++ native impl handle struct header from managed_api metadata."
    )
    parser.add_argument("--managed-api", required=True, help="Path to managed_api.json")
    parser.add_argument("--out", required=True, help="Output C++ header path")
    parser.add_argument("--check", action="store_true", help="Fail if output would change")
    parser.add_argument("--dry-run", action="store_true", help="Print output, do not write")
    args = parser.parse_args()

    metadata = load_json_object(Path(args.managed_api))
    content = render(metadata)

    return write_if_changed(Path(args.out), content, args.check, args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
