from __future__ import annotations

import argparse
import sys
from pathlib import Path

from ..core import AbiFrameworkError  # noqa: F401

_GITHUB_WORKFLOW_TEMPLATE = """\
# Generated by: abi_framework ci-config --provider github
# Validates ABI stability and regenerates language bindings on every push/PR.
#
# Exit codes: 0 = pass, 1 = ABI/codegen drift detected, 2 = framework error.
# Customize the paths, pip install target, and steps as needed.

name: ABI Check

on:
  push:
    branches: ["main", "master"]
  pull_request:

permissions:
  contents: read
  security-events: write  # required for SARIF upload

jobs:
  abi-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install abi-forge
        run: pip install {pip_target}

      - name: Verify ABI
        run: |
          abi_framework verify-all \\
            --config {config} \\
            {skip_binary_flag}\\
            --output-format annotations \\
            --sarif-report abi-results.sarif.json \\
            {fail_on_warnings_flag}--output-dir abi-verify-results

      - name: Check generated artifacts
        run: |
          abi_framework codegen \\
            --config {config} \\
            {skip_binary_flag}\\
            --check \\
            --output-format annotations

      - name: Upload SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: abi-results.sarif.json
          category: abi-forge
"""

_GITLAB_CI_TEMPLATE = """\
# Generated by: abi_framework ci-config --provider gitlab
# Validates ABI stability and regenerates language bindings on every push/MR.

stages:
  - abi-check

variables:
  ABI_CONFIG: "{config}"

abi-verify:
  stage: abi-check
  image: python:3.11-slim
  before_script:
    - pip install {pip_target}
  script:
    - |
      abi_framework verify-all \\
        --config "$ABI_CONFIG" \\
        {skip_binary_flag}\\
        --sarif-report gl-sast-report.json \\
        {fail_on_warnings_flag}--output-dir abi-verify-results
    - |
      abi_framework codegen \\
        --config "$ABI_CONFIG" \\
        {skip_binary_flag}\\
        --check
  artifacts:
    when: always
    paths:
      - abi-verify-results/
    reports:
      # GitLab SAST report (SARIF via Code Quality integration)
      sast: gl-sast-report.json
    expire_in: 1 week
"""


def command_ci_config(args: argparse.Namespace) -> int:
    provider: str = args.provider
    config: str = getattr(args, "config", "abi/config.json")
    output_path: str | None = getattr(args, "output", None)
    skip_binary: bool = bool(getattr(args, "skip_binary", False))
    fail_on_warnings: bool = bool(getattr(args, "fail_on_warnings", False))
    pip_target: str = getattr(args, "pip_target", "abi-forge")

    skip_binary_flag = "--skip-binary \\\n            " if skip_binary else ""
    fail_on_warnings_flag = "--fail-on-warnings \\\n            " if fail_on_warnings else ""

    if provider == "github":
        content = _GITHUB_WORKFLOW_TEMPLATE.format(
            config=config,
            skip_binary_flag=skip_binary_flag,
            fail_on_warnings_flag=fail_on_warnings_flag,
            pip_target=pip_target,
        )
        default_output = ".github/workflows/abi-check.yml"
    elif provider == "gitlab":
        content = _GITLAB_CI_TEMPLATE.format(
            config=config,
            skip_binary_flag=skip_binary_flag,
            fail_on_warnings_flag=fail_on_warnings_flag,
            pip_target=pip_target,
        )
        default_output = ".gitlab-ci-abi.yml"
    else:
        print(f"error: unknown provider '{provider}'. Use github or gitlab.", file=sys.stderr)
        return 2

    target = output_path or default_output
    out = Path(target).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"CI config written to {out}")
    return 0
