from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

from ..core import AbiFrameworkError  # noqa: F401

PLUGIN_NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_.\-]{1,127}$")

MANIFEST_TEMPLATE = """\
{{
  "schema_version": 1,
  "package": "{package}",
  "metadata": {{
    "description": "Custom ABI generator plugin."
  }},
  "plugins": [
    {{
      "name": "{name}",
      "version": "{version}",
      "description": "Generated by abi_framework new-plugin.",
      "entrypoint": {{
        "kind": "external",
        "command": [
          "{interpreter}",
          "{entrypoint_file}",
          "--idl", "{{idl}}",
          "--out", "{{repo_root}}/abi/generated/{{target}}/{short_name}.out",
          "{{check}}",
          "{{dry_run}}"
        ]
      }},
      "capabilities": {{
        "supports_check": true,
        "supports_dry_run": true,
        "deterministic_output": true,
        "requires_repo_root": true,
        "writes_managed_sources": false
      }},
      "contracts": {{
        "inputs": [
          {{"name": "idl", "path_arg": "--idl", "required": true}}
        ],
        "outputs": [
          {{"name": "output", "path_arg": "--out", "required": true}}
        ]
      }},
      "compatibility": {{
        "min_idl_schema_version": 1,
        "max_idl_schema_version": 1
      }}
    }}
  ]
}}
"""

PYTHON_GENERATOR_TEMPLATE = """\
#!/usr/bin/env python3
\"\"\"
ABI generator plugin: {name}
Generated by abi_framework new-plugin.
\"\"\"
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def generate(idl: dict, out_path: Path, check: bool, dry_run: bool) -> int:
    # TODO: implement your generator logic here
    # idl contains: functions, enums, structs, opaque_types, etc.
    content = "# Generated by {name}\\n"
    content += f"# Functions: {{', '.join(fn['name'] for fn in idl.get('functions', []))}}\\n"

    old = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
    if old == content:
        return 0
    if check:
        print(f"DRIFT: {{out_path}} is out of date", file=sys.stderr)
        return 1
    if dry_run:
        print(f"[dry-run] would write {{out_path}}")
        return 0
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"wrote {{out_path}}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="ABI generator: {name}")
    parser.add_argument("--idl", required=True, help="Path to IDL JSON")
    parser.add_argument("--out", required=True, help="Output file path")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    idl = json.loads(Path(args.idl).read_text(encoding="utf-8"))
    return generate(idl, Path(args.out), args.check, args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
"""

RUST_GENERATOR_TEMPLATE = """\
// ABI generator plugin: {name}
// Generated by abi_framework new-plugin.
// Build: cargo build --release
// Usage: {name} --idl <path> --out <path> [--check] [--dry-run]
use std::{{fs, path::PathBuf, process}};
use std::collections::HashMap;

fn main() {{
    let args: Vec<String> = std::env::args().collect();
    let mut idl_path: Option<&str> = None;
    let mut out_path: Option<&str> = None;
    let mut check = false;
    let mut dry_run = false;
    let mut i = 1;
    while i < args.len() {{
        match args[i].as_str() {{
            "--idl"     => {{ i += 1; idl_path  = Some(&args[i]); }}
            "--out"     => {{ i += 1; out_path  = Some(&args[i]); }}
            "--check"   => check   = true,
            "--dry-run" => dry_run = true,
            _ => {{}}
        }}
        i += 1;
    }}
    let idl_str = fs::read_to_string(idl_path.expect("--idl required")).unwrap();
    let _idl: serde_json::Value = serde_json::from_str(&idl_str).unwrap();
    // TODO: implement generator logic
    let content = format!("// Generated by {name}\\n");
    let out = PathBuf::from(out_path.expect("--out required"));
    let old = fs::read_to_string(&out).unwrap_or_default();
    if old == content {{ process::exit(0); }}
    if check {{
        eprintln!("DRIFT: {{}} is out of date", out.display());
        process::exit(1);
    }}
    if dry_run {{
        println!("[dry-run] would write {{}}", out.display());
        process::exit(0);
    }}
    if let Some(parent) = out.parent() {{ fs::create_dir_all(parent).unwrap(); }}
    fs::write(&out, &content).unwrap();
    println!("wrote {{}}", out.display());
}}
"""

GO_GENERATOR_TEMPLATE = """\
// ABI generator plugin: {name}
// Generated by abi_framework new-plugin.
// Build: go build -o {short_name} .
// Usage: {short_name} --idl <path> --out <path> [--check] [--dry-run]
package main

import (
    "encoding/json"
    "flag"
    "fmt"
    "os"
    "path/filepath"
)

func main() {{
    idlPath := flag.String("idl", "", "Path to IDL JSON")
    outPath := flag.String("out", "", "Output file path")
    check   := flag.Bool("check", false, "Check mode")
    dryRun  := flag.Bool("dry-run", false, "Dry-run mode")
    flag.Parse()

    data, err := os.ReadFile(*idlPath)
    if err != nil {{ fmt.Fprintln(os.Stderr, err); os.Exit(1) }}
    var idl map[string]any
    _ = json.Unmarshal(data, &idl)

    // TODO: implement generator logic
    content := fmt.Sprintf("// Generated by {name}\\n")

    existing, _ := os.ReadFile(*outPath)
    if string(existing) == content {{ os.Exit(0) }}
    if *check {{
        fmt.Fprintf(os.Stderr, "DRIFT: %s is out of date\\n", *outPath)
        os.Exit(1)
    }}
    if *dryRun {{
        fmt.Printf("[dry-run] would write %s\\n", *outPath)
        os.Exit(0)
    }}
    _ = os.MkdirAll(filepath.Dir(*outPath), 0o755)
    if err := os.WriteFile(*outPath, []byte(content), 0o644); err != nil {{
        fmt.Fprintln(os.Stderr, err); os.Exit(1)
    }}
    fmt.Printf("wrote %s\\n", *outPath)
}}
"""


def command_new_plugin(args: argparse.Namespace) -> int:
    name: str = args.name
    if not PLUGIN_NAME_PATTERN.match(name):
        print(
            f"error: plugin name '{name}' is invalid. "
            "Must match ^[a-z][a-z0-9_.\\-]{{1,127}}$",
            file=sys.stderr,
        )
        return 2

    lang: str = args.lang
    version: str = getattr(args, "version", "0.1.0")
    output_dir = Path(getattr(args, "output_dir", ".")).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    parts = name.rsplit(".", 1)
    package = parts[0] if len(parts) == 2 else name
    short_name = parts[-1]

    # Determine interpreter and entrypoint file
    if lang == "python":
        interpreter = "python3"
        entrypoint_file = f"{short_name}_generator.py"
    elif lang == "rust":
        interpreter = f"./{short_name}"
        entrypoint_file = f"{short_name}"
    else:  # go
        interpreter = f"./{short_name}"
        entrypoint_file = f"{short_name}"

    manifest_path = output_dir / "plugin.manifest.json"
    manifest_content = MANIFEST_TEMPLATE.format(
        package=package,
        name=name,
        version=version,
        short_name=short_name,
        interpreter=interpreter,
        entrypoint_file=entrypoint_file,
    )
    manifest_path.write_text(manifest_content, encoding="utf-8")
    print(f"created {manifest_path}")

    if lang == "python":
        gen_path = output_dir / f"{short_name}_generator.py"
        gen_content = PYTHON_GENERATOR_TEMPLATE.format(name=name)
        gen_path.write_text(gen_content, encoding="utf-8")
        print(f"created {gen_path}")
    elif lang == "rust":
        gen_path = output_dir / "main.rs"
        gen_content = RUST_GENERATOR_TEMPLATE.format(name=name, short_name=short_name)
        gen_path.write_text(gen_content, encoding="utf-8")
        print(f"created {gen_path}")
    else:  # go
        gen_path = output_dir / "main.go"
        gen_content = GO_GENERATOR_TEMPLATE.format(name=name, short_name=short_name)
        gen_path.write_text(gen_content, encoding="utf-8")
        print(f"created {gen_path}")

    print(f"\nPlugin '{name}' scaffolded in {output_dir}")
    print(f"Next steps:")
    print(f"  1. Implement your generator logic in {gen_path.name}")
    print(f"  2. Test with: abi_framework test-plugin --manifest {manifest_path}")
    print(f"  3. Reference the manifest in your abi/config.json target generators")
    return 0
